images:
    # Source: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
    registrar: cr.yandex/yc-marketplace/yandex-cloud/csi-s3/csi-node-driver-registrar1731688358770397682609004996982070545465802304702:v1.2.0
    # Source: quay.io/k8scsi/csi-provisioner:v2.1.0
    provisioner: cr.yandex/yc-marketplace/yandex-cloud/csi-s3/csi-provisioner1731688358770397682609004996982070545465802304702:v2.1.0
    # Main image
    csi: cr.yandex/yc-marketplace/yandex-cloud/csi-s3/csi-s3-driver1731688358770397682609004996982070545465802304702:0.42.1
storageClass:
    # Specifies whether the storage class should be created
    create: true
    # Name
    name: csi-s3
    # Use a single bucket for all dynamically provisioned persistent volumes
    singleBucket: ""
    # mounter to use - either geesefs, s3fs or rclone (default geesefs)
    mounter: geesefs
    # GeeseFS mount options
    mountOptions: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
    # Volume reclaim policy
    reclaimPolicy: Delete
    # Annotations for the storage class
    # Example:
    # annotations:
    #   storageclass.kubernetes.io/is-default-class: "true"
    annotations: {}
secret:
    # Specifies whether the secret should be created
    create: true
    # Name of the secret
    name: csi-s3-secret
    # S3 Access Key
    accessKey: ""
    # S3 Secret Key
    secretKey: ""
    # Endpoint
    endpoint: https://storage.yandexcloud.net
    # Region
    region: ""
tolerations:
    all: false
    node: []
    controller: []
nodeSelector: {}
kubeletPath: /var/lib/kubelet
