# Copyright 2021-2024 Alexey Remizov <alexey@remizov.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

output "id" {
  description = "ID of the service account."

  value = yandex_iam_service_account.default.id
}

output "name" {
  description = "Name of the service account."

  value = yandex_iam_service_account.default.name
}

output "static_access_keys" {
  description = "Properties of the static access keys."

  value = yandex_iam_service_account_static_access_key.default

  sensitive = true
}

output "service_account_keys" {
  description = <<DESCRIPTION
  Properties of the service account keys, including
  JSON representation of service account key
  as generated by `yc iam key create --output key.json`.
  DESCRIPTION

  value = local.service_account_keys

  sensitive = true
}
